### ISSUE TITLE
Cannot handle nested prefix

### ISSUE THREAD

**Issue by garbled1** [tobus3000/isc_dhcp_netbox#4]
(venv) root@zosma:/opt/isc_dhcp_netbox/isc_dhcp_netbox# isc_dhcp_netbox 
None
None
Traceback (most recent call last):
  File "/opt/isc_dhcp_netbox/venv/bin/isc_dhcp_netbox", line 11, in <module>
    load_entry_point('isc-dhcp-netbox==0.0.1', 'console_scripts', 'isc_dhcp_netbox')()
  File "/opt/isc_dhcp_netbox/venv/lib/python3.9/site-packages/isc_dhcp_netbox-0.0.1-py3.9.egg/isc_dhcp_netbox/main.py", line 37, in main
  File "/opt/isc_dhcp_netbox/venv/lib/python3.9/site-packages/isc_dhcp_netbox-0.0.1-py3.9.egg/isc_dhcp_netbox/netbox.py", line 43, in get_ip_prefix
Warning: Could not derive prefix of 192.168.11.144

![image](https://github.com/tobus3000/isc_dhcp_netbox/assets/6556271/0dacc8cb-1ab7-46a8-a38a-d1dee02f9a7f)

**Comment by tobus3000** [comment]
Hi there!

Thanks for pointing this out.  
I could replicate the problem and it should be fixed in [v0.0.2](https://github.com/tobus3000/isc_dhcp_netbox/releases/tag/v0.0.2).  
Tested against Netbox: 3.7.0.

Setup: Parent prefix 192.168.0.0/16 with /24 child prefixes.  
![image](https://github.com/tobus3000/isc_dhcp_netbox/assets/34127251/a4e47036-9143-4b25-a0d5-727bc6ba6eb9)
![image](https://github.com/tobus3000/isc_dhcp_netbox/assets/34127251/75d2e3e5-313e-486b-aa96-9388211d5a71)
